using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// ’e‚ğŠÇ—
public class Bullet : MonoBehaviour
{
    // ’e‚Ì‘¬“x
    [SerializeField]
    float bulletSpeed;
    // ‹@”\‚ğg‚¤
    Rigidbody rigidbody;
    // õ–½
    [SerializeField]
    float lifeSpan;
    // Œo‰ßŠÔ‚ğŒv‘ª
    float currentTime;
    // ‚P‰ñ‚Ì—Í‚Å¨‚¢—Ç‚­”ò‚Î‚·
    void Fry()
    {
        rigidbody.AddForce(transform.forward * bulletSpeed, ForceMode.VelocityChange);
    }
    // ‰½‚©‚É“–‚½‚Á‚½‚ç
    void OnCollisionEnter(Collision collision)
    {
        Destroy(gameObject);
    }
    // Start is called before the first frame update
    void Start()
    {
        // Åy‘c‚È‚Ì‚ÅŒo‰ß‚Í‚O
        currentTime = 0;

        rigidbody = GetComponent<Rigidbody>();

        // ’e‚ğ”ò‚Î‚·
        Fry();
    }
    void Update()
    {
        // Œo‰ßŠÔ‚ğ‰ÁZ
        currentTime += Time.deltaTime;
        // ¶‘¶ŠÔ‚ªõ–½‚ğ’´‚¦‚½‚ç
        if (currentTime > lifeSpan)
        {
            Destroy(gameObject);
        }
    }
}